# Generated by Django 3.2.12 on 2024-11-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('exercise_type', models.CharField(max_length=50)),
                ('body_part', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('rating_description', models.CharField(max_length=255)),
            ],
        ),
    ]
