# Generated by Django 5.1.3 on 2024-11-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_clientprofile_trainerprofile_user_delete_exercise_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserGymbo',
        ),
    ]
