# Generated by Django 5.1.3 on 2024-11-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainerprofile_clients_trainerprofile_whatsapp_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='exercises',
            field=models.ManyToManyField(to='core.exercise'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='reviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trainerprofile'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='weight',
            field=models.JSONField(default=list),
        ),
    ]
