# Generated by Django 5.1.3 on 2024-11-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0003_rename_user_usergymbo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGymbo',
            new_name='User',
        ),
    ]
