# Generated by Django 3.2.12 on 2024-11-25 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_trainer_user'),
        ('core', '0004_rename_usergymbo_user'),
    ]

    operations = [
    ]
